// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "swim_service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// OrganizerRepository is an autogenerated mock type for the OrganizerRepository type
type OrganizerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: organizer
func (_m *OrganizerRepository) Create(organizer *domain.Organizer) error {
	ret := _m.Called(organizer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Organizer) error); ok {
		r0 = rf(organizer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *OrganizerRepository) GetByID(id int) (*domain.Organizer, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Organizer
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Organizer, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Organizer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organizer)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrganizerRepository creates a new instance of OrganizerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizerRepository {
	mock := &OrganizerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
