// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "swim_service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// AthleteRepository is an autogenerated mock type for the AthleteRepository type
type AthleteRepository struct {
	mock.Mock
}

// CreateAthlete provides a mock function with given fields: athlete
func (_m *AthleteRepository) CreateAthlete(athlete *domain.Athlete) error {
	ret := _m.Called(athlete)

	if len(ret) == 0 {
		panic("no return value specified for CreateAthlete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Athlete) error); ok {
		r0 = rf(athlete)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *AthleteRepository) GetByID(id int) (*domain.Athlete, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Athlete
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Athlete, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Athlete); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Athlete)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: id, newStatus
func (_m *AthleteRepository) UpdateStatus(id int, newStatus string) error {
	ret := _m.Called(id, newStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(id, newStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAthleteRepository creates a new instance of AthleteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAthleteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AthleteRepository {
	mock := &AthleteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
