// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "swim_service/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CompetitionRepository is an autogenerated mock type for the CompetitionRepository type
type CompetitionRepository struct {
	mock.Mock
}

// AddResult provides a mock function with given fields: compID, result
func (_m *CompetitionRepository) AddResult(compID int, result domain.Result) error {
	ret := _m.Called(compID, result)

	if len(ret) == 0 {
		panic("no return value specified for AddResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, domain.Result) error); ok {
		r0 = rf(compID, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: comp
func (_m *CompetitionRepository) Create(comp *domain.Competition) error {
	ret := _m.Called(comp)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Competition) error); ok {
		r0 = rf(comp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *CompetitionRepository) GetAll() ([]*domain.Competition, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*domain.Competition
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*domain.Competition, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*domain.Competition); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Competition)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllResultsByDistance provides a mock function with given fields: distance
func (_m *CompetitionRepository) GetAllResultsByDistance(distance string) ([]domain.Result, error) {
	ret := _m.Called(distance)

	if len(ret) == 0 {
		panic("no return value specified for GetAllResultsByDistance")
	}

	var r0 []domain.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.Result, error)); ok {
		return rf(distance)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.Result); ok {
		r0 = rf(distance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(distance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAthleteResultsByDistance provides a mock function with given fields: athleteID, distance
func (_m *CompetitionRepository) GetAthleteResultsByDistance(athleteID int, distance string) ([]domain.Result, error) {
	ret := _m.Called(athleteID, distance)

	if len(ret) == 0 {
		panic("no return value specified for GetAthleteResultsByDistance")
	}

	var r0 []domain.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) ([]domain.Result, error)); ok {
		return rf(athleteID, distance)
	}
	if rf, ok := ret.Get(0).(func(int, string) []domain.Result); ok {
		r0 = rf(athleteID, distance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(athleteID, distance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAthleteResultsByPeriod provides a mock function with given fields: ctx, athleteID, startDate, endDate
func (_m *CompetitionRepository) GetAthleteResultsByPeriod(ctx context.Context, athleteID int, startDate time.Time, endDate time.Time) ([]domain.Result, error) {
	ret := _m.Called(ctx, athleteID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetAthleteResultsByPeriod")
	}

	var r0 []domain.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) ([]domain.Result, error)); ok {
		return rf(ctx, athleteID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) []domain.Result); ok {
		r0 = rf(ctx, athleteID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, time.Time, time.Time) error); ok {
		r1 = rf(ctx, athleteID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *CompetitionRepository) GetByID(id int) (*domain.Competition, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Competition
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Competition, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Competition); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Competition)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCompetitionRepository creates a new instance of CompetitionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompetitionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompetitionRepository {
	mock := &CompetitionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
