// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analytics/get/{id}": {
            "post": {
                "description": "Get detailed analytics for a specific athlete including performance metrics and trends",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get athlete analytics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Athlete ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Analytics period filters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AthleteAnalyticsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with athlete analytics",
                        "schema": {
                            "$ref": "#/definitions/dto.AthleteAnalyticsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid athlete ID or request format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Athlete not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/athletes/create": {
            "post": {
                "description": "Create a new athlete with the provided information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "athletes"
                ],
                "summary": "Create a new athlete",
                "parameters": [
                    {
                        "description": "Athlete information",
                        "name": "athlete",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateAthleteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully created athlete",
                        "schema": {
                            "$ref": "#/definitions/dto.AthleteResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/athletes/get/{id}": {
            "get": {
                "description": "Retrieve athlete information by athlete ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "athletes"
                ],
                "summary": "Get athlete by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Athlete ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved athlete",
                        "schema": {
                            "$ref": "#/definitions/dto.AthleteResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid athlete ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Athlete not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/athletes/update/{id}": {
            "patch": {
                "description": "Update the status of an existing athlete",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "athletes"
                ],
                "summary": "Update athlete status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Athlete ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New status information",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateAthleteStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated athlete status",
                        "schema": {
                            "$ref": "#/definitions/dto.AthleteResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Athlete not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/competitions/add/{id}": {
            "post": {
                "description": "Add a new result (swimmer's time) to an existing competition",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "results"
                ],
                "summary": "Add result to competition",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Competition ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Result information",
                        "name": "result",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddResultRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully added result",
                        "schema": {
                            "$ref": "#/definitions/dto.ResultResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Competition not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/competitions/create": {
            "post": {
                "description": "Create a new swimming competition with the provided information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "competitions"
                ],
                "summary": "Create a new competition",
                "parameters": [
                    {
                        "description": "Competition information",
                        "name": "competition",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCompetitionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully created competition",
                        "schema": {
                            "$ref": "#/definitions/dto.CompetitionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/competitions/get-all": {
            "get": {
                "description": "Retrieve a list of all competitions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "competitions"
                ],
                "summary": "Get all competitions",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved competitions list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.CompetitionResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/competitions/get/{id}": {
            "get": {
                "description": "Retrieve competition information by competition ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "competitions"
                ],
                "summary": "Get competition by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Competition ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved competition",
                        "schema": {
                            "$ref": "#/definitions/dto.CompetitionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid competition ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Competition not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Authenticate user and receive JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "User login credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful, returns JWT token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or request format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/organizers/create": {
            "post": {
                "description": "Create a new competition organizer with the provided information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizers"
                ],
                "summary": "Create a new organizer",
                "parameters": [
                    {
                        "description": "Organizer information",
                        "name": "organizer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateOrganizerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully created organizer",
                        "schema": {
                            "$ref": "#/definitions/dto.OrganizerResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/organizers/get/{id}": {
            "get": {
                "description": "Retrieve organizer information by organizer ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizers"
                ],
                "summary": "Get organizer by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Organizer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved organizer",
                        "schema": {
                            "$ref": "#/definitions/dto.OrganizerResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid organizer ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Organizer not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Register a new user with login and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User successfully registered",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or request format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "User already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/register-special": {
            "post": {
                "description": "Register a user with special role and permissions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a special user (e.g., admin, organizer)",
                "parameters": [
                    {
                        "description": "Special user registration data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterSpecialRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Special user successfully registered",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or request format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "User already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AddResultRequest": {
            "description": "Request for adding a swimmer's result to a competition",
            "type": "object",
            "properties": {
                "athlete_id": {
                    "type": "integer"
                },
                "distance": {
                    "type": "string"
                },
                "place": {
                    "type": "integer"
                },
                "time_sec": {
                    "type": "number"
                }
            }
        },
        "dto.AthleteAnalyticsRequest": {
            "description": "Request for retrieving athlete analytics with optional period filters",
            "type": "object",
            "properties": {
                "athlete_id": {
                    "type": "integer"
                },
                "period_end": {
                    "type": "string"
                },
                "period_start": {
                    "type": "string"
                }
            }
        },
        "dto.AthleteAnalyticsResponse": {
            "description": "Detailed analytics data for an athlete",
            "type": "object",
            "properties": {
                "athlete_id": {
                    "type": "integer"
                },
                "average_time": {
                    "type": "number"
                },
                "best_time": {
                    "type": "number"
                },
                "distance_breakdown": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DistanceStats"
                    }
                },
                "period_end": {
                    "type": "string"
                },
                "period_start": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ResultResponse"
                    }
                },
                "total_competitions": {
                    "type": "integer"
                },
                "total_distance": {
                    "type": "string"
                },
                "worst_time": {
                    "type": "number"
                }
            }
        },
        "dto.AthleteResponse": {
            "description": "Response with athlete details",
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.CompetitionResponse": {
            "description": "Response with competition details",
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "organizer": {
                    "type": "integer"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ResultResponse"
                    }
                }
            }
        },
        "dto.CreateAthleteRequest": {
            "description": "Request for creating a new athlete",
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.CreateCompetitionRequest": {
            "description": "Request for creating a new swimming competition",
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizer_id": {
                    "type": "integer"
                }
            }
        },
        "dto.CreateOrganizerRequest": {
            "description": "Request for creating a new competition organizer",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.DistanceStats": {
            "description": "Statistical data for swimming results by distance",
            "type": "object",
            "properties": {
                "average_time": {
                    "type": "number"
                },
                "best_time": {
                    "type": "number"
                },
                "count": {
                    "type": "integer"
                },
                "distance": {
                    "type": "string"
                },
                "worst_time": {
                    "type": "number"
                }
            }
        },
        "dto.LoginRequest": {
            "description": "Request for user authentication",
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "dto.OrganizerResponse": {
            "description": "Response with organizer details",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.RegisterSpecialRequest": {
            "description": "Request for registering a user with special role (admin, organizer, etc.)",
            "type": "object",
            "required": [
                "login",
                "password",
                "role"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "user",
                        "admin"
                    ]
                }
            }
        },
        "dto.RegisterUserRequest": {
            "description": "Request for registering a new regular user",
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "dto.ResultResponse": {
            "description": "Response with swimmer's result details",
            "type": "object",
            "properties": {
                "athlete_id": {
                    "type": "integer"
                },
                "distance": {
                    "type": "string"
                },
                "place": {
                    "type": "integer"
                },
                "time_sec": {
                    "type": "number"
                }
            }
        },
        "dto.UpdateAthleteStatusRequest": {
            "description": "Request for updating athlete status",
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
